name: MobSpawn
main: com.SkyIsland.MobSpawn.MobSpawn
version: 0.1
commands:
  spawn_mob:
    description: spawns a mob with super special id ID relative to the player
    usage: /spawn_mob [ID]
    permissions: MobSpawn.spawn_mob
    permission-message: You don't have permission to use spawn_mob